// Base de données simplifiée des codes postaux français
export const postalCodeData: Record<string, string[]> = {
  '01': ['Bourg-en-Bresse', 'Oyonnax', 'Bellegarde-sur-Valserine', 'Gex', 'Ferney-Voltaire'],
  '02': ['Laon', 'Saint-Quentin', 'Soissons', 'Château-Thierry', 'Chauny'],
  '03': ['Moulins', 'Montluçon', 'Vichy', 'Cusset', 'Yzeure'],
  '04': ['Digne-les-Bains', 'Manosque', 'Sisteron', 'Forcalquier', 'Castellane'],
  '05': ['Gap', 'Briançon', 'Embrun', 'Veynes', 'Laragne-Montéglin'],
  '06': ['Nice', 'Cannes', 'Antibes', 'Grasse', 'Cagnes-sur-Mer', 'Le Cannet', 'Menton', 'Vallauris'],
  '07': ['Privas', 'Annonay', 'Aubenas', 'Tournon-sur-Rhône', 'Guilherand-Granges'],
  '08': ['Charleville-Mézières', 'Sedan', 'Rethel', 'Revin', 'Givet'],
  '09': ['Foix', 'Pamiers', 'Saint-Girons', 'Lavelanet', 'Tarascon-sur-Ariège'],
  '10': ['Troyes', 'Romilly-sur-Seine', 'La Chapelle-Saint-Luc', 'Saint-André-les-Vergers', 'Sainte-Savine'],
  '11': ['Carcassonne', 'Narbonne', 'Béziers', 'Castelnaudary', 'Limoux'],
  '12': ['Rodez', 'Millau', 'Villefranche-de-Rouergue', 'Saint-Affrique', 'Decazeville'],
  '13': ['Marseille', 'Aix-en-Provence', 'Arles', 'Martigues', 'Aubagne', 'Istres', 'Salon-de-Provence'],
  '14': ['Caen', 'Cherbourg-en-Cotentin', 'Lisieux', 'Bayeux', 'Vire Normandie'],
  '15': ['Aurillac', 'Saint-Flour', 'Mauriac', 'Riom-ès-Montagnes', 'Maurs'],
  '16': ['Angoulême', 'Cognac', 'Soyaux', 'Ruelle-sur-Touvre', 'La Couronne'],
  '17': ['La Rochelle', 'Saintes', 'Rochefort', 'Royan', 'Aytré'],
  '18': ['Bourges', 'Vierzon', 'Saint-Amand-Montrond', 'Saint-Doulchard', 'Mehun-sur-Yèvre'],
  '19': ['Tulle', 'Brive-la-Gaillarde', 'Ussel', 'Malemort', 'Corrèze'],
  '20': ['Ajaccio', 'Bastia', 'Porto-Vecchio', 'Bonifacio', 'Calvi'],
  '21': ['Dijon', 'Beaune', 'Chenôve', 'Talant', 'Quetigny'],
  '22': ['Saint-Brieuc', 'Lannion', 'Dinan', 'Plérin', 'Loudéac'],
  '23': ['Guéret', 'Aubusson', 'La Souterraine', 'Bourganeuf', 'Sainte-Feyre'],
  '24': ['Périgueux', 'Bergerac', 'Sarlat-la-Canéda', 'Coulounieix-Chamiers', 'Trélissac'],
  '25': ['Besançon', 'Montbéliard', 'Pontarlier', 'Audincourt', 'Valentigney'],
  '26': ['Valence', 'Romans-sur-Isère', 'Montélimar', 'Bourg-lès-Valence', 'Pierrelatte'],
  '27': ['Évreux', 'Vernon', 'Louviers', 'Val-de-Reuil', 'Gisors'],
  '28': ['Chartres', 'Dreux', 'Lucé', 'Châteaudun', 'Vernouillet'],
  '29': ['Brest', 'Quimper', 'Concarneau', 'Landerneau', 'Guipavas'],
  '30': ['Nîmes', 'Alès', 'Bagnols-sur-Cèze', 'Beaucaire', 'Saint-Gilles'],
  '31': ['Toulouse', 'Colomiers', 'Tournefeuille', 'Muret', 'Blagnac'],
  '32': ['Auch', 'Condom', 'Fleurance', 'Lectoure', 'Mirande'],
  '33': ['Bordeaux', 'Mérignac', 'Pessac', 'Talence', 'Villenave-d\'Ornon'],
  '34': ['Montpellier', 'Béziers', 'Sète', 'Lunel', 'Agde'],
  '35': ['Rennes', 'Saint-Malo', 'Fougères', 'Vitré', 'Cesson-Sévigné'],
  '36': ['Châteauroux', 'Issoudun', 'Le Blanc', 'La Châtre', 'Argenton-sur-Creuse'],
  '37': ['Tours', 'Joué-lès-Tours', 'Chinon', 'Amboise', 'Saint-Pierre-des-Corps'],
  '38': ['Grenoble', 'Saint-Martin-d\'Hères', 'Échirolles', 'Vienne', 'Bourgoin-Jallieu'],
  '39': ['Lons-le-Saunier', 'Dole', 'Saint-Claude', 'Champagnole', 'Morez'],
  '40': ['Mont-de-Marsan', 'Dax', 'Biscarrosse', 'Saint-Paul-lès-Dax', 'Tarnos'],
  '41': ['Blois', 'Romorantin-Lanthenay', 'Vendôme', 'Mer', 'Saint-Laurent-Nouan'],
  '42': ['Saint-Étienne', 'Roanne', 'Saint-Chamond', 'Firminy', 'Montbrison'],
  '43': ['Le Puy-en-Velay', 'Monistrol-sur-Loire', 'Yssingeaux', 'Brioude', 'Langeac'],
  '44': ['Nantes', 'Saint-Nazaire', 'Rezé', 'Saint-Sébastien-sur-Loire', 'Orvault'],
  '45': ['Orléans', 'Montargis', 'Olivet', 'Fleury-les-Aubrais', 'Saint-Jean-de-Braye'],
  '46': ['Cahors', 'Figeac', 'Gourdon', 'Souillac', 'Gramat'],
  '47': ['Agen', 'Villeneuve-sur-Lot', 'Marmande', 'Tonneins', 'Le Passage'],
  '48': ['Mende', 'Florac Trois Rivières', 'Saint-Chély-d\'Apcher', 'Langogne', 'La Canourgue'],
  '49': ['Angers', 'Cholet', 'Saumur', 'Avrillé', 'Trélazé'],
  '50': ['Saint-Lô', 'Cherbourg-en-Cotentin', 'Granville', 'Avranches', 'Coutances'],
  '51': ['Reims', 'Châlons-en-Champagne', 'Épernay', 'Vitry-le-François', 'Sainte-Menehould'],
  '52': ['Chaumont', 'Saint-Dizier', 'Langres', 'Nogent', 'Wassy'],
  '53': ['Laval', 'Mayenne', 'Château-Gontier-sur-Mayenne', 'Ernée', 'Évron'],
  '54': ['Nancy', 'Vandœuvre-lès-Nancy', 'Villers-lès-Nancy', 'Toul', 'Pont-à-Mousson'],
  '55': ['Bar-le-Duc', 'Verdun', 'Commercy', 'Saint-Mihiel', 'Ligny-en-Barrois'],
  '56': ['Vannes', 'Lorient', 'Lanester', 'Ploemeur', 'Hennebont'],
  '57': ['Metz', 'Thionville', 'Montigny-lès-Metz', 'Sarreguemines', 'Forbach'],
  '58': ['Nevers', 'Cosne-Cours-sur-Loire', 'Decize', 'Clamecy', 'Varzy'],
  '59': ['Lille', 'Roubaix', 'Tourcoing', 'Dunkerque', 'Villeneuve-d\'Ascq'],
  '60': ['Beauvais', 'Compiègne', 'Creil', 'Senlis', 'Nogent-sur-Oise'],
  '61': ['Alençon', 'Flers', 'Argentan', 'L\'Aigle', 'Domfront en Poiraie'],
  '62': ['Arras', 'Calais', 'Boulogne-sur-Mer', 'Lens', 'Liévin'],
  '63': ['Clermont-Ferrand', 'Chamalières', 'Cournon-d\'Auvergne', 'Riom', 'Issoire'],
  '64': ['Pau', 'Bayonne', 'Anglet', 'Biarritz', 'Hendaye'],
  '65': ['Tarbes', 'Lourdes', 'Aureilhan', 'Bagnères-de-Bigorre', 'Argelès-Gazost'],
  '66': ['Perpignan', 'Canet-en-Roussillon', 'Saint-Cyprien', 'Argelès-sur-Mer', 'Elne'],
  '67': ['Strasbourg', 'Schiltigheim', 'Haguenau', 'Illkirch-Graffenstaden', 'Sélestat'],
  '68': ['Mulhouse', 'Colmar', 'Saint-Louis', 'Illzach', 'Wittenheim'],
  '69': ['Lyon', 'Villeurbanne', 'Vénissieux', 'Saint-Priest', 'Caluire-et-Cuire'],
  '70': ['Vesoul', 'Héricourt', 'Lure', 'Gray', 'Luxeuil-les-Bains'],
  '71': ['Mâcon', 'Chalon-sur-Saône', 'Le Creusot', 'Autun', 'Montceau-les-Mines'],
  '72': ['Le Mans', 'Sablé-sur-Sarthe', 'Allonnes', 'Coulaines', 'La Flèche'],
  '73': ['Chambéry', 'Aix-les-Bains', 'Albertville', 'Saint-Jean-de-Maurienne', 'Bourg-Saint-Maurice'],
  '74': ['Annecy', 'Thonon-les-Bains', 'Annemasse', 'Chamonix-Mont-Blanc', 'Rumilly'],
  '75': ['Paris'],
  '76': ['Rouen', 'Le Havre', 'Sotteville-lès-Rouen', 'Saint-Étienne-du-Rouvray', 'Dieppe'],
  '77': ['Meaux', 'Melun', 'Chelles', 'Pontault-Combault', 'Savigny-le-Temple'],
  '78': ['Versailles', 'Boulogne-Billancourt', 'Argenteuil', 'Montreuil', 'Saint-Denis'],
  '79': ['Niort', 'Bressuire', 'Thouars', 'Parthenay', 'Melle'],
  '80': ['Amiens', 'Abbeville', 'Montdidier', 'Albert', 'Péronne'],
  '81': ['Albi', 'Castres', 'Mazamet', 'Graulhet', 'Carmaux'],
  '82': ['Montauban', 'Castelsarrasin', 'Moissac', 'Caussade', 'Montech'],
  '83': ['Toulon', 'La Seyne-sur-Mer', 'Hyères', 'Fréjus', 'Draguignan'],
  '84': ['Avignon', 'Orange', 'Carpentras', 'Cavaillon', 'Apt'],
  '85': ['La Roche-sur-Yon', 'Les Sables-d\'Olonne', 'Challans', 'Olonne-sur-Mer', 'Fontenay-le-Comte'],
  '86': ['Poitiers', 'Châtellerault', 'Buxerolles', 'Saint-Benoît', 'Montmorillon'],
  '87': ['Limoges', 'Saint-Junien', 'Couzeix', 'Panazol', 'Isle'],
  '88': ['Épinal', 'Saint-Dié-des-Vosges', 'Gérardmer', 'Golbey', 'Remiremont'],
  '89': ['Auxerre', 'Sens', 'Joigny', 'Avallon', 'Migennes'],
  '90': ['Belfort', 'Delle', 'Beaucourt', 'Danjoutin', 'Valdoie'],
  '91': ['Évry-Courcouronnes', 'Corbeil-Essonnes', 'Massy', 'Savigny-sur-Orge', 'Sainte-Geneviève-des-Bois'],
  '92': ['Boulogne-Billancourt', 'Nanterre', 'Courbevoie', 'Colombes', 'Asnières-sur-Seine'],
  '93': ['Saint-Denis', 'Montreuil', 'Aubervilliers', 'Aulnay-sous-Bois', 'Drancy'],
  '94': ['Créteil', 'Vitry-sur-Seine', 'Champigny-sur-Marne', 'Saint-Maur-des-Fossés', 'Ivry-sur-Seine'],
  '95': ['Argenteuil', 'Cergy', 'Garges-lès-Gonesse', 'Franconville', 'Goussainville']
};

export function getCitiesByPostalCode(postalCode: string): string[] {
  const departmentCode = postalCode.substring(0, 2);
  return postalCodeData[departmentCode] || [];
}

export function isValidPostalCode(postalCode: string): boolean {
  return /^\d{5}$/.test(postalCode) && postalCodeData.hasOwnProperty(postalCode.substring(0, 2));
}